PANTALLA_ANCHO = 800
PANTALLA_ALTO = 600
FPS = 60 #Frames por segundo

TAMANIO_MOSAICO = 32

CAPA = [1, 2, 3]
#CAPA_JUGADOR = 3
#CAPA_ARBOL = 2
#CAPA_PISO = 1

VELOCIDAD_JUGADOR = 3
VELOCIDAD_ENEMIGO = 2

ROJO =  (255,  0,  0)
NEGRO = (  0,  0,  0)
BLANCO =(255,255,255)
AZUL =  (  0,  0,255)

MAPA = [
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAA......J....................AAAAA',
    'AAAAA...........................AAAAA',
    'AAAAA..........E................AAAAA',
    'AAAAA..........................AAAAAA',
    'AAAAA...........................AAAAA',
    'AAAAA..........................AAAAAA',
    'AAAAA..........................AAAAAA',
    'AAAAA...........................AAAAA',
    'AAAAA...........................AAAAA',
    'AAAAA...........................AAAAA',
    'AAAAA...........................AAAAA',
    'AAAAA..AAAAA.........E..........AAAAA',
    'AAAAA..AAAAA....................AAAAA',
    'AAAAA...........................AAAAA',
    'AAAAA........................AAAAAAAA',
    'AAAAA...........................AAAAA',
    'AAAAA...........................AAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
]